<ns:Trigger xmlns:ns="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileDescriptor>
        <FileName>UDB-G68-TEST3-6-DV.xml</FileName>
        <SizeInBytes>15614</SizeInBytes>
        <Sender>Testtool02</Sender>
        <SendersFileId>Udbetalingsanmodning</SendersFileId>
        <Recipients>SP_OIR_TRANSFER</Recipients>
    </FileDescriptor>
    <FileContentDescriptor>
        <SFTPDynamicRoutingInfo>
            <InfRef>SF1590_C_IF02</InfRef>
            <SenderIt-system>6cfc6b02-25c9-45b6-894a-6f1aab52c9e9</SenderIt-system>
            <SenderAuthority>urn:oio:cvr-nr:55133018</SenderAuthority>
            <TransactionId>0c587315-7586-44f5-8bf5-a834e89c13cf</TransactionId>
            <SenderTimestamp>2016-12-12T08:50:00+02:00</SenderTimestamp>
	    <RecipientIt-system></RecipientIt-system>
            <RecipientAuthority>urn:oio:cvr-nr:55133018</RecipientAuthority>
        </SFTPDynamicRoutingInfo>
    </FileContentDescriptor>
</ns:Trigger>
