<ns:Trigger xmlns:ns="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileDescriptor>
        <FileName>UDB-G68-TEST11-12_14-16-FOR.xml</FileName>
        <SizeInBytes>19511</SizeInBytes>
        <Sender>Testtool02</Sender>
        <SendersFileId>Udbetalingsanmodning</SendersFileId>
        <Recipients>SP_OIR_TRANSFER</Recipients>
    </FileDescriptor>
    <FileContentDescriptor>
        <SFTPDynamicRoutingInfo>
            <InfRef>SF1590_C_IF02</InfRef>
            <SenderIt-system>6c0e4e7e-2128-4e0d-a074-fb0eebd7e133</SenderIt-system>
            <SenderAuthority>urn:oio:cvr-nr:55133018</SenderAuthority>
            <TransactionId>dc13f9bc-6b1b-4cd8-a4be-315b414bc6ef</TransactionId>
            <SenderTimestamp>2016-12-12T08:51:00+02:00</SenderTimestamp>
	    <RecipientIt-system></RecipientIt-system>
            <RecipientAuthority>urn:oio:cvr-nr:55133018</RecipientAuthority>
        </SFTPDynamicRoutingInfo>
    </FileContentDescriptor>
</ns:Trigger>
