<ns:Trigger xmlns:ns="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileDescriptor>
        <FileName>UDB-G68-TEST7-10_13-FOR.xml</FileName>
        <SizeInBytes>19508</SizeInBytes>
        <Sender>Testtool02</Sender>
        <SendersFileId>Udbetalingsanmodning</SendersFileId>
        <Recipients>SP_OIR_TRANSFER</Recipients>
    </FileDescriptor>
    <FileContentDescriptor>
        <SFTPDynamicRoutingInfo>
            <InfRef>SF1590_C_IF02</InfRef>
            <SenderIt-system>6cfc6b02-25c9-45b6-894a-6f1aab52c9e9</SenderIt-system>
            <SenderAuthority>urn:oio:cvr-nr:29189722</SenderAuthority>
            <TransactionId>dc13f9bc-6b1b-4cd8-a4be-315b414bc6ed</TransactionId>
            <SenderTimestamp>2016-10-15T08:51:00+02:00</SenderTimestamp>
	    <RecipientIt-system></RecipientIt-system>
            <RecipientAuthority>urn:oio:cvr-nr:29189722</RecipientAuthority>
        </SFTPDynamicRoutingInfo>
    </FileContentDescriptor>
</ns:Trigger>
