<ns:Trigger xmlns:ns="http://serviceplatformen.dk/xml/wsdl/soap11/SFTP/1/types">
    <FileDescriptor>
        <FileName>UDB-G68-TEST1-HIT.xml</FileName>
        <SizeInBytes>3932</SizeInBytes>
        <Sender>Testtool02</Sender>
        <SendersFileId>Udbetalingsanmodning</SendersFileId>
        <Recipients>SP_OIR_TRANSFER</Recipients>
    </FileDescriptor>
    <FileContentDescriptor>
        <SFTPDynamicRoutingInfo>
            <InfRef>SF1590_C_IF02</InfRef>
            <SenderIt-system>6cfc6b02-25c9-45b6-894a-6f1aab52c9e9</SenderIt-system>
            <SenderAuthority>urn:oio:cvr-nr:29189722</SenderAuthority>
            <TransactionId>5a4adce9-ba5c-4325-982d-c034af063909</TransactionId>
            <SenderTimestamp>2016-12-12T08:48:00+02:00</SenderTimestamp>
			<RecipientIt-system></RecipientIt-system>
            <RecipientAuthority>urn:oio:cvr-nr:29189722</RecipientAuthority>
        </SFTPDynamicRoutingInfo>
    </FileContentDescriptor>
</ns:Trigger>
